language: ruby
rvm:
  - 2.1.0

env:
  - RAKE_TARGET=spec
  - RAKE_TARGET=assets:precompile

script: RAILS_ENV=test bin/rake ${RAKE_TARGET}

addons:
  postgresql: "9.3"
  code_climate:
    repo_token: "285312ea70ecd70b1f57eae62f9d9f4b53b5169928b9dba6645a28b45d1dbeea"

cache:
  bundler: true
  apt: true

bundler_args: --without development,production

before_script:
  - mkdir -p tmp/cache
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bin/rake db:reset
